### ISSUE TITLE
GT-5.10 TO-DO list

### ISSUE THREAD

**Issue by Dragon2488** [Blood-Asp/GT5-Unofficial#1196]
- [x] Moving all MetaValueItems to constants, for easy access. Like MetaItemList.someStaticConstant = this.addItem(...)...;
- [x] Fixes to gregtech.api.recipes package (possibly rewrite?)
- [ ] Fixes and advancements to worldgen
- [x] New gui system for machines. Features widgets as graphics elements, aims to make creation of machine guis, elements and advanced elements simpler.
- [ ] Fixes of old meta tile entities to work with new system (very big task)
- [ ] Make all last things work and compile
- [ ] First alpha build <---
- [ ] Bugfixes
- [ ] Possible meta tile entities fixes after testing feedback
- [ ] JEI support
- [ ] second alpha build <---
- [ ] Bugfixes,
- [ ] reimplement cover system
- [ ] first beta build <---

**Comment by Exidex** [comment]
For every one who came here to check progress.
 We have new repo -> https://github.com/Gregtech-CE/Gregtech
